# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class G < Formula
  desc "generator thing"
  homepage "https://github.com/quinn/g"
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/quinn/g/releases/download/v0.0.6/g_Darwin_x86_64.tar.gz"
      sha256 "0db6b412ab24e23806f522e335c0f918d45b93a5a3b4602004577f31f8e3a1f2"

      def install
        bin.install "g"
      end
    end
    on_arm do
      url "https://github.com/quinn/g/releases/download/v0.0.6/g_Darwin_arm64.tar.gz"
      sha256 "19c9a6badd0fd1e164edb93a91ef40e3b8837bad6a9afc53eea6f36bf27aa11b"

      def install
        bin.install "g"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn/g/releases/download/v0.0.6/g_Linux_x86_64.tar.gz"
        sha256 "24b11cbf1abb407770b889ebac8ba6b2be432c0f5537a2c89d5ad582632ade73"

        def install
          bin.install "g"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/quinn/g/releases/download/v0.0.6/g_Linux_arm64.tar.gz"
        sha256 "d2388003a7c6ad67febc307ffa4a605ced9225b704604b19b53884d7a89404cf"

        def install
          bin.install "g"
        end
      end
    end
  end

  test do
    system "#{bin}/g -help"
  end
end
